### ISSUE TITLE
where's the license?

### ISSUE THREAD

**Issue by burdickjp** [Xyl2k/TSA-Travel-Sentry-master-keys#4] opened 2015-09-10 18:59 UTC
May I suggest you use the CERN open hardware license?
http://www.ohwr.org/documents/294

**Comment by 3TroubleMonster** [comment] 2015-09-10 19:23
Fuck u

**Comment by MS3FGX** [comment] 2015-09-10 20:16
Licensing for something like this strikes me as a bit tricky. As it stands, the files presented are duplicates of real-world objects which we don't have the rights to. Just because you make a digital representation/duplicate of an object doesn't mean you can now assert your rights as it's owner; the rightful owner is still whoever created it.

So for the existing TSA key STL files, I would think the safest approach would be a very permissive license, something like a 3 clause BSD. That would give attribution, but stop short of putting restrictions on the how and why the files can be used. My specific concern with the CERN license is the very opening of their prerequisite:

_Authorship/ownership of the design must be clear and undisputed. Only the legal owner of the rights in the hardware design may decide under what conditions to make it available._

Looking ahead, I think it would be a good idea to create some new STL (maybe even SCAD) files for a set of keys **based** on the original TSA set. In that case, I agree a robust license like the CERN OHL would be a logical choice.

**Comment by burdickjp** [comment] 2015-09-10 22:00
That is a very, very good point. I'm still wrapping my head around hardware licenses. As you've demonstrated, they can be very tricky in comparison to software licenses.

**Comment by 3TroubleMonster** [comment] 2015-09-10 22:12
Stopv

**Comment by Xyl2k** [comment] 2015-09-17 09:12
in the U.S. keys are utilitiarian objects and as such are not eligible for copyright protection, mechanical keys and locks are instead protected by patents, but that is a non-copyright restriction.
As it's master keys, the reproduced keys in themselves may contravene patent laws -if they where offered for sale- but i think it's fine here as we don't sell, just release to public.

From wiki: https://en.wikipedia.org/wiki/Key_blank
https://en.wikipedia.org/wiki/Key_%28lock%29#Do_not_duplicate_key

"keys stamped with "Do not duplicate" or "It is unlawful to duplicate this key" are, with few exceptions, perfectly legal to duplicate."
"There is no direct legal sanction in the US for someone who copies a key that is stamped do not duplicate"

What's about the WTFPL license ?

**Comment by MS3FGX** [comment] 2015-09-17 14:44
As you say, traditional open software licensees (like the GPL) are not very good choices for hardware because they deal with the concept of copyright. Open hardware licenses, on the other hand (like CERN and TAPR) are designed with patentable objects in mind. So CERN would be an applicable license to a non-copyrightable object, but there is still the issue of who really owns the design.

We could simply release them as public domain, but I thought using a BSD license would be better as it would at least require attribution to the original project. So people would be free to do whatever they wish with the objects, as long as they said where they got them from.

WTFPL is essentially just a public domain license (since the concept of public domain doesn't exist in all countries, the WTFPL is an explicit statement of the concept), but is often avoided because it isn't a very professional statement. It's also considered redundant since there are existing licenses that do the same thing, so it has not been approved by the OSI.

For what it's worth, the FSF suggests the use of a Creative Commons license for 3D models of utilitarian objects: http://www.gnu.org/licenses/license-list.html#Designs

CC0 could be used if the goal is to put the models in the public domain.

**Comment by johnnyxmas** [comment] 2015-09-17 14:48
Totally valid. They "real" keys don't have a patent# on them, and I have to imagine if they were, the TSA would have tried a Cease & Desist by now, or sent Github a takedown. Even if they ARE patented, we're still free to do this because  I think [Creative Commons Zero](https://en.wikipedia.org/wiki/Creative_Commons_license#Zero_.2F_public_domain) is more politically-correct, but has the same sentiment.

As far as U.S. reverse-engineering laws go, it looks like we're able to RE these keys if it's for the purposes of [developing new locks that will be compliant with them](https://en.wikipedia.org/wiki/Reverse_engineering#Overlap_with_patent_law). That's just my interpretation though. Again, if they're not even patented in the first place, then we're free to do anything.

My only real concern, and this is just a personal thing, is I don't like the idea of other people making money off of something they didn't design. I release all of my stuff on Thingiverse as "Creative Commons 3.0 Attribution / Non-Commercial" meaning they must give credit to me for the design, and aren't allowed to sell anything based off it. They're able to reproduce and distribute for free, however. As the majority of each of these designs is based on Xylit0l's work, I'd say he gets the final say on licensing.

**Comment by Xyl2k** [comment] 2015-09-17 15:07
I don't like the idea of someone selling these too, it would be totally unethical.

@johnnyxmas: since you guys also help on TSA models you have your word to say, that why i don't want to take a decision alone.
Creative Commons 3.0 Attribution / Non-Commercial seem a good choice, if you agree too (MS3FGX?) let's close this and go for CC BY-NC 3.0 ?

**Comment by MS3FGX** [comment] 2015-09-17 17:04
Like Johnny, I license my creations on Thingiverse under CC BY-NA as well. I'm fine with that license and would have no objection to that becoming what we use here. 

The only question I would have is does the non-commercial aspect mean it would be more difficult to have them printed by the user?

For example, does the TOS for services like Shapeways and 3D Hubs prohibit users from printing objects with a non-commercial license?

**Comment by johnnyxmas** [comment] 2015-09-17 18:46
No, as they're selling the printing service, not the keys. If Shapeways started selling the keys themselves on their site then yes, it would prevent that (which is good). Also, I bet their ToS prevents users from even asking them to print the keys.

**Comment by MS3FGX** [comment] 2015-09-17 19:48
Good point, we're already probably in a gray area with the commercial printing outfits.

Let's go for CC BY-NC 3.0 then.

**Comment by johnnyxmas** [comment] 2015-09-17 20:48
Done. Added LICENSE.md and updated the README file to reflect it, plus some more recent information.

**Closed as completed by johnnyxmas** 2015-09-17 20:48 UTC
